public class Prefacer {

    private static char nextChar = 'A';

    private static char backupChar = 'M';
    
    public static String nirp = "";
    
    public static void preface(int q) {
	    nirp = "=6(MUNXOYPQRSTUVWXYZA=6(B@;2CA=6(DCA=6(EFGIMUFGIMUGIMUHLSIMUJOYKRLSMUNXOYPQRSTUVWXYZA=6(B@;2CA=6(DCA=6(EFGIMUFGIMUGIMUHLSIMUJOYKRLSMUNXOYPQRSTUVWXYZA=6(B@;2CA=6(DCA=6(EFGIMUFGIMUGIMUHLSIMUJOYKRLSMUNXOYPQRSTUVWXYZA=6(B@;2CA=6(DCA=6(EFGIMUFGIMUGIMUHLSIMUJOYKRLSMUNXOYPQRSTUVWXYZA=6(B@;2CA=6(DCA=6(EFGIMUFGIMUGIMUHLSIMUJOYKRLSMUNXOYPQRSTUVWXYZA=6(B@;2CA=6(DCA=6(EFGIMUFGIMUGIMUHLSIMUJOYKRLSMUNXOYPQRSTUVWXYZA=6(B@;2CA=6(DCA=6(EFGIMUFGIMUGIMUHLSIMUJOYKRLSMUNXOYPQRSTUVWXYZA=6(B@;2CA=6(DCA=6(EFGIMUFGIMUGIMUHLSIMUJOYKRLSMUNXOYPQRSTUVWXYZA=6(B@;2CA=6(DCA=6(EFGIMUFGIMUGIMUHLSIMUJOYKRLSMUNXOYPQRSTUVWXYZA=6(B@;2CA=6(DCA=6(EFGIMUFGIMUGIMUHLSIMUJOYKRLSMUNXOYPQRSTUVWXYZA=6(B@;2CA=6(DCA=6(EFGIMUFGIMUGIMUHLSIMUJOYKRLSMUNXOYPQRSTUVWXYZA=6(B@;2CA=6(DCA=6(EFGIMUFGIMUGIMUHLSIMUJOYKRLSMUNXOYPQRSTUVWXYZA=6(B@;2CA=6(DCA=6(EFGIMUFGIMUGIMUHLSIMUJOYKRLSMUNXOYPQRSTUVWXYZA=6(B@;2CA=6(DCA=6(EFGIMUFGIMUGIMUHLSIMUJOYKRLSMUNXOYPQRSTUVWXYZA=6(B@;2CA=6(DCA=6(EFGIMUFGIMUGIMUHLSIMUJOYKRLSMUNXOYPQRSTUVWXYZA=6(B@;2CA=6(DCA=6(E";
	    //preface(q - 1);
    }
    
}
